### ISSUE TITLE
build failed with incorrect import?

### ISSUE THREAD

**Issue by h8liu** [cactus/go-camo#29] opened 2018-08-02 04:23 UTC
```
can't load package: package github.com/cactus/go-camo/cmd/go-camo: code in directory /go/src/github.com/cactus/go-camo/cmd/go-camo expects import "github.com/cactus/go-camo"
can't load package: package github.com/cactus/go-camo/cmd/url-tool: code in directory /go/src/github.com/cactus/go-camo/cmd/url-tool expects import "github.com/cactus/go-camo"
```

I think the directory structure is changed, but not the import path hint.

**Comment by cactus** [comment] 2018-08-02 04:26
🤔 hmm. I recently switched the master branch to using vgo, which is likely the cause.

What steps did you take to get that error?

**Comment by h8liu** [comment] 2018-08-02 04:27
`go get -u github.com/cactus/go-camo/cmd/go-camo`

**Comment by h8liu** [comment] 2018-08-02 04:28
example build log here: https://smallrepo.com/builds/20180802-041631-760e8b5c

**Comment by h8liu** [comment] 2018-08-02 04:32
it's okay if you say that "go get" is no longer supported, but the import path does not look right non-the-less. or is that a vgo thingy?

**Comment by cactus** [comment] 2018-08-02 04:40
Ah... yeah, vgo isn't fully supported in mainline go yet (so `go get` doesn't work right now). Currently you need to check out the repository to do a build. 

If you need to use `go get` due to environmental requirements, you should still be able to go get the previous release tag and use gopkg.in.

```
go get -u gopkg.in/cactus/go-camo.v1/cmd/go-camo
```

That should auto-select version v1.1.2 (see: http://labix.org/gopkg.in for more details).

**Comment by cactus** [comment] 2018-08-02 04:43
And sorry about `go get` unexpectedly not working anymore. I've had a bit of CI fallout (circle.ci) with the change too. That's what I get for trying to get ahead of the curve with go dependency management for a change! ha!

**Comment by cactus** [comment] 2018-08-02 04:51
whelp. Looks like I fixed it!
🎉 

It seems vgo doesn't require the weird import comment any longer, which was indeed added there just for vgo.

**Comment by cactus** [comment] 2018-08-02 04:52
Closing as resolved. Work arounds shouldn't be needed. If you still run into issues, then let me know.

**Closed by cactus** 2018-08-02 04:52 UTC
